export const errorCode:Record<string, string> = {
    '3000':"Barang dagangan gratis diterima",
    '3001':"Jumlah berlian kurang",
    '3002':"Barang tidak ditemukan",
    '3003':"Pengguna tidak ditemukan oleh Uid",
    '1000':"Terjadi kesalahan yang tidak diketahui, Silahkan hubungi layanan pelanggan.",
    '1001':"Login Apple gagal, silahkan coba lagi",
    '1002':"Login Google gagal, silahkan coba lagi",
    '1003':"Login Facebook gagal, silahkan coba lagi",
    '1004':"Nomor perangkat kosong",
    '1005':"Nomor perangkat sudah ada",
    '1006':"Kotak surat hanya dapat diubah satu kali, anda sudah mengubahnya.",
    '1007':"Prop tidak ada",
    '1008':"Prop ini akan digunakan secara otomatis",
    '1009':"Kesalahan status pencapaian",
    '1010':"Anda telah mengklaim hadiah",
    '1011':"Hadiah tidak ada",
    '1012':"Login Google gagal, silahkan coba lagi",
    '1013':"Login Google gagal, silahkan coba lagi",
    '1014':"Login Facebook gagal, silahkan coba lagi",
    '1015':"Login Facebook gagal, silahkan coba lagi",
    '1016':"Login Facebook gagal, silahkan coba lagi",
    '1017':"Login Apple gagal, silahkan coba lagi",
    '1018':"Login Apple gagal, silahkan coba lagi",
    '1019':"ID Apple tidak ada",
    '1020':"Akun pengguna telah diblokir, silahkan hubungi layanan pelanggan",
    '1021':"Nomor telepon tidak boleh kosong",
    '1022':"Format nomor telepon salah, silahkan masukkan 8-14 angka",
    '1023':"Pengiriman pesan gagal, silahkan coba lagi",
    '1024':"Kata sandi tidak cukup kuat, masukkan minimal 8 karakter.",
    '1025':"Operasi terlalu sering, silahkan coba lagi nanti",
    '1026':"UID tidak boleh kosong",
    '1027':"Nama pengguna atau kata sandi salah",
    '1028':"Kode verifikasi salah, silahkan masukkan kembali",
    '-1':"Kesalahan server",
    '-2':"Kerusakan jaringan terjadi nanti"
}
